### ISSUE TITLE
there is a bug that the TextView can not work with the android:textColor in xml in 1.0.1

### ISSUE THREAD

**Issue by wlfcolin** [dvdciri/MultiChoiceRecyclerView#1]
there is a bug that the TextView can not work with the android:textColor in xml in 1.0.1，if i compile the aar myself with master branch codes，it works fine.

**Comment by dvdciri** [comment]
Thank's for the report! I'll work on it soon, if you've got any possible solution feel free to make a pull request! 

If you're using this library in an app let me know :)

**Comment by dvdciri** [comment]
@wlfcolin Can you explain what is not working or give some more detail about it? 
I've made some tests and everything is okay using android:textColor in xml..

**Comment by dvdciri** [comment]
@wlfcolin  Still waiting for more details about the issue, if nothing comes in a couple of days i'll assume that everything is okay for now!
Thanks

**Comment by dvdciri** [comment]
Close because seems to be fixed
