### ISSUE TITLE
Keep the state of the toolbar unchanged

### ISSUE THREAD

**Issue by dvdciri** [dvdciri/MultiChoiceRecyclerView#11]
If you set a toolbar icon (home as up icon) on the original toolbar and you set the MultiChoiceToolbar, whenever the deselectAll action is made and the old toolbar is restored it'll remove the icon not keeping the state of the toolbar unchanged.

A workaround for now is to set the `MultiChoiceSelectionListener` and at `OnDeselectAll()` reset the icon again.

**Comment by dvdciri** [comment]
I'm starting working on this in the 1.1.8 along with some consistent improvement on the MultiChoiceToolbar.

**Comment by ScottMellors** [comment]
Seems to be resolved in the 1.1.7 release. Updated today and behaving how I was expecting it to!

**Comment by dvdciri** [comment]
It shouldn't be resolved, the only way is to restore to icon in the onDeselectAll

**Comment by dvdciri** [comment]
Anyway, in the 1.1.8 release there will be a Builder for the MultiChoiceToolbar so you can pass you toolbar icon in and will be restore when needed. Available soon.

**Comment by dvdciri** [comment]
Available in 1.1.8:
Use this method to set the icon and action for the MultiChoiceToolbarBuilder
`Builder setIcon(int icon, View.OnClickListener action)`
