### ISSUE TITLE
performVibrate permission issue 

### ISSUE THREAD

**Issue by davidHarush** [dvdciri/MultiChoiceRecyclerView#16]
Form Android 6.0+  performVibrate method need permission handle

**Comment by dvdciri** [comment]
@davidHarush Thanks for letting me know, in v1.1.9 there will be a check for permission granted, is interest of whoever is going to implement the library to make sure it has the correct permission at runtime before the user starts interacting with the application.

**Comment by dvdciri** [comment]
@davidHarush Wait a second, just realising that `android.permission.VIBRATE` should be automatically granted as permission and doesn't need runtime check. Can you add more details?

**Comment by davidHarush** [comment]
Yes, It's defined as normal permission, but it's crash for my from that spot, i will check again...

**Comment by dvdciri** [comment]
I'm still going to add a permission granted check to avoid any kind of permission related issues.. 

Please let me know asap so we can give a resolution to the issue. 
Thanks

**Comment by davidHarush** [comment]
It's  now, i'm sorry  :-(
