### ISSUE TITLE
Why minSdkVersion is not 15 

### ISSUE THREAD

**Issue by sagar15795** [dvdciri/MultiChoiceRecyclerView#2]
I have run this code with minSdkVersion 15 . And it works fine. Is there any problem with API 15

**Comment by dvdciri** [comment]
There was a problem with API 15 some time ago and i've decided to keep 17 as minSdk, if you've got something working and ready to test just fell free to create a pull request and i'll include in the next release, otherwise I'll do it for the next release.

Thanks for letting me know.

**Comment by dvdciri** [comment]
Just released 1.1.2 with the minSdkVersion to 15

**Comment by sagar15795** [comment]
Thank for enhancement
