### ISSUE TITLE
defaultItemViewClickListener is not getting called on click 

### ISSUE THREAD

**Issue by shimiglide** [dvdciri/MultiChoiceRecyclerView#25]
### Context

defaultItemViewClickListener is not getting called on click. it is called on scroll 
so i have no way to get click 

### Steps to reproduce

just implement

**Comment by dvdciri** [comment]
@shimiglide As you can see [here](https://github.com/dvdciri/MultiChoiceRecyclerView/blob/master/library/multichoicerecyclerview/src/main/java/com/davidecirillo/multichoicerecyclerview/MultiChoiceAdapter.java#L32) the defaultOnClickListener is set only if is not null, make sure you're overriding the method providing the correct implementation and calling super on the View Holder

**Comment by dvdciri** [comment]
Ok, just saw it has been closed, maybe say why so we can help other people with the same problem.

Thanks

**Comment by shimiglide** [comment]
i overrided the method defaultItemViewClickListener but did not return a new View.OnClickListener like this
    @Override
    protected View.OnClickListener defaultItemViewClickListener(GalleryViewHolder holder, int position) {
        Log.i("shimi", "defaultItemViewClickListener: in defaultItemViewClickListener position = "+position);
        ItemClicked itemClicked = mItemClicked.get();
        if(itemClicked != null){
            //itemClicked.onItemClicked(mMessageList.get(position), position);
        }
        return super.defaultItemViewClickListener(holder, position);
    }

**Comment by shimiglide** [comment]
now that i am doing 
    @Override
    protected View.OnClickListener defaultItemViewClickListener(GalleryViewHolder holder, final int position) {
        return new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.i("shimi", "defaultItemViewClickListener: in defaultItemViewClickListener position = "+position);
                ItemClicked itemClicked = mItemClicked.get();
                if(itemClicked != null){
                    itemClicked.onItemClicked(mMessageList.get(position), position);
                }
            }
        };
    }
it is working

**Comment by dvdciri** [comment]
Thanks, i'm probably gonna change that bit in order to provide more flexibility are setting the default click listener, also for long click.

**Comment by shimiglide** [comment]
PS it is not the best implementation to create a new listener on every bind. you should change that

**Comment by dvdciri** [comment]
@shimiglide What do you propose instead of creating it every time?

**Comment by shimiglide** [comment]
it should be in the viewHolder then it is only created one time onCreateViewHolder

**Comment by shimiglide** [comment]
http://stackoverflow.com/questions/33845846/why-is-adding-an-onclicklistener-inside-onbindviewholder-of-a-recyclerview-adapt

**Comment by shimiglide** [comment]
also setActive() should pass the holder not the view this way you don't need to findViewById every time.

**Comment by dvdciri** [comment]
Thanks for the advices, the onClickListener is impossible to add inside the creation of the ViewHolder because of the way the library works, the click listener is in the process of binding items, it can be different as you scroll and can be changes on the go internally because of the recycling feature.

I'll think about passing the holder for better implementation, but whenever you bind your view into the holder you're still calling findViewById inside it.

**Comment by dvdciri** [comment]
I'm gonna close this one. If you want you can create a PR with changes and i'll be more that happy to review it. 

(Keep in mind #22)
