### ISSUE TITLE
Wrong class used in README.md for layout xml

### ISSUE THREAD

**Issue by lcasale** [dvdciri/MultiChoiceRecyclerView#26]
In your README.md in the implementation example you have...

`<com.davidecirillo.multichoicesample.MultiChoiceRecyclerView
        android:id="@+id/multiChoiceRecyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />`

when it should be...

`<com.davidecirillo.multichoicerecyclerview.MultiChoiceRecyclerView
        android:id="@+id/multiChoiceRecyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />`

**Comment by dvdciri** [comment]
Cool, good spot! Will fix that!

Thanks
