### ISSUE TITLE
Comments, Feedback and New Features

### ISSUE THREAD

**Issue by dvdciri** [dvdciri/MultiChoiceRecyclerView#28]
I wanted to create this issue just for getting **comment and feedback** from the new release 2.0.0. Also I'm open to advices for **new functionalities** and improvements.

Please comments below if want to help!

Thanks

**Comment by hardysim** [comment]
@dvdciri what about **actions in the toolbar** for the selected items. E.g. I want to delete all selected items by clicking a trash-icon in the (ActionMode-)Toolbar. It this possible with this release?

**Comment by dvdciri** [comment]
@hardysim The thing about actions is that you need to prepare and create your option menu within the `onCreateOptionMenu` method of activities and fragments, and then listed for clicks with the `onOptionItemSelected`, i'm not sure if this is a good idea..

I could add some predefined actions but i'm not in control of the list of items displayed so i can't modify it and notify.. i should add some way to hold the item list in my adapter and manage it..

**Comment by hardysim** [comment]
Yes. I just realized that the toolbar-actions are not changed (only the icon and the title). I thought the lib would start an `ActionMode`...

I managed to get it working by using `setMultiChoiceSelectionListener()` and calling `invalidateOptionsMenu()` in every callback. In `onCreateOptionsMenu()` I check for selection with `getSelectedItemCount()` and toggle the visibility of my toolbar-actions. Not perfect, but working.

**Comment by hardysim** [comment]
Can we get the following?

- some kind of `isSelected()` instead of `getSelectedItemCount()`
- use string-res in `MultiChoiceToolbar.Builder.setTitles()`
- not forced to set `setTitles()` in a *Builder* - if needed I think the constructor would be a better place

So far nice improvement over the last version :+1:

**Comment by dvdciri** [comment]
@hardysim Thanks for the advices! Will definitely take a look at them! Maybe create three different issues and we can carry on over there!

**Comment by hardysim** [comment]
I created issues for each:

> some kind of isSelected() instead of getSelectedItemCount()
https://github.com/dvdciri/MultiChoiceRecyclerView/issues/29

> use string-res in MultiChoiceToolbar.Builder.setTitles()
https://github.com/dvdciri/MultiChoiceRecyclerView/issues/30

> not forced to set setTitles() in a Builder
https://github.com/dvdciri/MultiChoiceRecyclerView/issues/31

**Comment by hardysim** [comment]
And an other one - #32

**Comment by hardysim** [comment]
And more - #33

**Comment by hardysim** [comment]
Even more (feature request) - #34

**Comment by hardysim** [comment]
More more more ;)

#35 , #36

**Comment by dvdciri** [comment]
@hardysim Thanks for the issues and help, it would be great if you can follow the template while creating the issues and if applicable provide screenshots/log. 

I'm (slowly) looking into them. =)

**Comment by hardysim** [comment]
> Also, if you fancy helping (again) why don't you submit some PR and share the knowledge??

Yeah, I'm just about to start today :-) I tried forking on the weekend but had trouble referencing issues from your project in my fork.

Is there some best-practice how to work on issues here (fork, create feature-branch with correct reference to issue, create PR to original project..)?

**Comment by dvdciri** [comment]
Just create a PR for merging in develop in this repo, don't need to merge, please keep it simple and targeted on the singole issue, and give a proper name referencing the issue (I might set up some custom contribution guidelines) thanks

**Comment by dvdciri** [comment]
FYI 2.1.0 is not out with some fixed thanks for the help @hardysim!

**Comment by dvdciri** [comment]
I'm gonna close this one. Thanks to @hardysim for contributing and raising new defect =) did good work!
