### ISSUE TITLE
Can we get isSelected()?

### ISSUE THREAD

**Issue by hardysim** [dvdciri/MultiChoiceRecyclerView#29]
> from https://github.com/dvdciri/MultiChoiceRecyclerView/issues/28#issuecomment-274800577

Can we get some kind of `isSelected()` instead of `getSelectedItemCount()`

**Comment by dvdciri** [comment]
Yes we can! =) It was in a previous version but i decided to remove it for some reasons. Will implement it.

**Comment by dvdciri** [comment]
I thought you want something like `isSelected(int position)`, in that case i'm gonna close this because as i said, you can use `getSelectedItemCount() > 0` and this is what i added it for.

**Comment by hardysim** [comment]
Hmm, `isSelected(int position)` is a good idea though. Should we change the title of the issue and re-open it? :-)

**Comment by dvdciri** [comment]
We can open another issue for the `isSelected(int position)`, it's a quick add
