### ISSUE TITLE
Can we use string-res in MultiChoiceToolbar.Builder.setTitles()

### ISSUE THREAD

**Issue by hardysim** [dvdciri/MultiChoiceRecyclerView#30]
> from https://github.com/dvdciri/MultiChoiceRecyclerView/issues/28#issuecomment-274800577

**Comment by dvdciri** [comment]
@hardysim This is a quick one, you also do it if you want =)

**Comment by hardysim** [comment]
sure, I'll add this tomorrow

**Comment by dvdciri** [comment]
Closing cause it's in develop.
