### ISSUE TITLE
Preserve selection on device-rotation

### ISSUE THREAD

**Issue by hardysim** [dvdciri/MultiChoiceRecyclerView#35]
Is it possible to set the selected positions manually? E.g. when rotating the device, the selection is lost and I want to store / re-apply it programmatically.

**Comment by dvdciri** [comment]
You can manually select items here https://github.com/dvdciri/MultiChoiceRecyclerView/blob/master/library/multichoicerecyclerview/src/main/java/com/davidecirillo/multichoicerecyclerview/MultiChoiceAdapter.java#L82

**Comment by hardysim** [comment]
> only if is the multi choice mode or single click choice mode is activated

How do I activate this mode? When the activity is re-created (after device-rotation), I need to activate this mode and select the positions.

**Comment by dvdciri** [comment]
The MCM is activated automatically when an item is selected. The single choice mode is activated manually, see documentation.

When the device rotate, is it resetting all the selected positions and is not in multi choice mode? Then if the MCM is not active, the select() method won't do anything cause there are no item selected, I might need to take a look at this as well..

**Comment by hardysim** [comment]
Exactly, `mIsInMultiChoiceMode` and `mIsInSingleClickMode` are both `false` in `MultiChoiceAdapter#select()` when trying to select the positions from my `savedInstanceState` (calling in `Fragment#onViewCreated()`.

**Comment by dvdciri** [comment]
Might be interesting if you can take a look at this.. =)

**Comment by hardysim** [comment]
I think the problem in my case is, that I'm re-creating the `MultiChoiceAdapter` in `onViewCreated()` and therefor all information is lost.

It might work, saving the result of `getSelectedItemList()` in `onSaveInstanceState()` and restore it by calling `select()` but as I mentioned, this only works when MCM is active (which I cannot alter from the outside).

---

What's the plan for this? Make MCM become active when `select()` is called?

**Comment by dvdciri** [comment]
Not sure, cause the logic behind it is, if in multi choice mode, the first should be selected with a long, click, if not in multi choice but in single click mode, then all the items can be selected with one click. Said that, it makes sense that the `select()` is not allowing you to select if is not in one of the to modes.

Given the fact that there's documentation on the `select()` method explaining this, and now that i'm thinking more about this, you can use the `setSingleClickMode(true)` and the user the `select()` method to do your selections, and then re-call `setSingleClickMode(false)` to restore the state, so i don't think this should be open. It should work that way

**Comment by dvdciri** [comment]
Just checked and the application, is currently restoring the state to nothing selected. So this is definitely a bug that needs fix. 

There might be different fix for this, i'll need to take a look

**Comment by hardysim** [comment]
So you mean that I could do the following?

```java
setSingleClickMode(true);

for (int position : selectedItems) {
  select(position);
}

setSingleClickMode(false);
```

But this does not work currently and you're going to investigate (on a different issue)?

**Comment by dvdciri** [comment]
Yeah, the above snipped should work correctly.. it's a workaround though but there is still a bug in the lib cause if you change orientation everything will be deselected.

**Comment by dvdciri** [comment]
Closing this one, because checking into the code there was a bug with the sample app that was always initialising the adapter. Fixing this in another PR and opening a new one related to a bug inside the library, that when you change the orientation, i'll show an empty list of data.
