### ISSUE TITLE
remove develop-branch

### ISSUE THREAD

**Issue by hardysim** [dvdciri/MultiChoiceRecyclerView#42]
Currently you have `master` and `develop` and feature-branches start from `develop`. But it seems like you forget to merge from `master` to `develop` from time to time after a release is made.

I could think of just removing `develop` and start all feature-branches from `master` (like the GitHub-flow suggests). This would be more easy for you and for contributors (who don't need to merge to branches to stay up-to-date).

What do you think?

---

https://guides.github.com/introduction/flow/

**Comment by dvdciri** [comment]
Nope, master is protected, the only code that goes in is the release branch took out from develop, following the git-workflow, in fact every time I branch out for a release I use the UI tools from source tree that allow me to create feature branches, release branches from develop and then once a release is made and we close it, it'll automatically merge everything into developing and update master. If I forgot to close the release, this is another story 😂
