### ISSUE TITLE
setActive is not trigger

### ISSUE THREAD

**Issue by tuancoltech** [dvdciri/MultiChoiceRecyclerView#45]
I have setup my Adapter as same as the guidelines but dont know why my setActive is not getting triggered.
Could you look into this and tell me why?

Thank you.

[ApprovalRequestAdapter.zip](https://github.com/dvdciri/MultiChoiceRecyclerView/files/766220/ApprovalRequestAdapter.zip)

**Comment by dvdciri** [comment]
Not sure how to help, we need more info for that.. try with the following:
- Are you attaching the adapter to the RecyclerView so `onAttachedToRecyclerView` will be called?
- Are you calling super.onBindViewHolder(...) in your adapter
- Try to check the sample app and see what are you missing..

**Comment by amarilindra** [comment]
I'm facing the same issue. How can I debug the issue? 

I'm already calling super.onBindViewHolder(...)
