### ISSUE TITLE
New Feature: isSelected(int position)

### ISSUE THREAD

**Issue by hardysim** [dvdciri/MultiChoiceRecyclerView#46]
There should be a method to report if a specific position is currently selected.

---

See discussion in #29.

**Comment by hardysim** [comment]
@dvdciri my implementation would be

```java
public boolean isSelected(int position) {
        return getSelectedItemListInternal().contains(position);
    }
```

As you mentioned in #29 that's maybe too easy (as you can use `getSelectedItemList()` and do the `contains()` yourself.

Should be dismiss this?

**Comment by dvdciri** [comment]
Yeah that is what i was saying... closing it
