### ISSUE TITLE
Avoid always updating the view if not needed

### ISSUE THREAD

**Issue by dvdciri** [dvdciri/MultiChoiceRecyclerView#5]
Every time the RecyclerView is scrolled, the onBindViewHolder method is fired and views are updated (whether is active or deactive). This will cause a bad effect if the setActive method is activating/deactivating the items with an animation.

**Comment by dvdciri** [comment]
For now, a workaround for this is to not update the views if the multi choice selection is active (selected items > 0)..

**Comment by yogieeka** [comment]
i'm trying this on itemSelected, and work

MultiChoiceRecyclerView.setMultiChoiceSelectionListener(new MultiChoiceSelectionListener() {
            @Override
            public void OnItemSelected(int selectedPosition, int itemSelectedCount, int allItemCount) {
                MultiChoiceRecyclerView.setAdapter(adapter);
                adapter.notifyDataSetChanged();
      }
}

**Comment by dvdciri** [comment]
Why are you doing that? The RecyclerView works as per normal usage, you don't need to call `notifyDataSetChanged()` when something is selected because that method is already called before the callback is fired. 

The issue is about the fact that every time you scroll the RecyclerView the onBindViewHolder is called and, to keep everything up to date, I'm refreshing the state of the current View. 
This will cause a bad effect when you override the `setActive(View view, boolean state) ` and provide an implementation that use Animation (in relation to the state activa/disactive).

I'm working on it, I'll fix it as soon as possible, if you've got any suggestions feel free to fork, I'll be more than happy to see your pull request. 

Thanks =)

**Comment by dvdciri** [comment]
Closing because there will be some improvements in v1.1.9 on that.
