### ISSUE TITLE
There is no deselect(int position) method

### ISSUE THREAD

**Issue by kcywek** [dvdciri/MultiChoiceRecyclerView#51]
Please provide deselect(int position) method in MultiChoiceAdapter. There is select(int position) method but there is no deselect. Thanks in advance.

**Comment by dvdciri** [comment]
Yes, that definitely makes sense! Creating the PR in days. Thanks

**Comment by dvdciri** [comment]
Created PR #52 for this along with refactor to the select(int position) method.

**Comment by dvdciri** [comment]
#52 is in develop now, the feature will be available with the next release. Closing this
