### ISSUE TITLE
Hi Davide, is there a way to get the position of the selected item in my recylerview once it is active? Or at least get the positions of the active rows in the recyclerview

### ISSUE THREAD

**Issue by mlaferla** [dvdciri/MultiChoiceRecyclerView#56]
### Context
I need to get the position of the selected active items in my recyclerview to then use it to create a group chat. Is there a way to get the position of the selected item in the `setActive()` method?

**Comment by dvdciri** [comment]
Yes, if you look at the available APIs in the MultiChoiceAdapter you'll see that there are method for getting the selected items. And other useful ones. Check out the Readme file and the Features file for more info!

**Comment by mlaferla** [comment]
I need the position of the selected item in the setActive method. This method only has two parameters which are status and view. How can I use these to get the position of my selected item?

**Comment by dvdciri** [comment]
The set Active method is not supposed to know about the position of the object, think about it like a bind view, you just need to apply the UI changes. Why do you need the position here?

**Comment by mlaferla** [comment]
Because I am then adding the from the view to an arraylist. Don't worry I found a way around it.

**Comment by mohsinabid** [comment]
@mlaferla please tell me how you solved this problem of getting position in set Active
