### ISSUE TITLE
NullPointerException when setting the title of "selected items" to null

### ISSUE THREAD

**Issue by jdamacena** [dvdciri/MultiChoiceRecyclerView#58]
### Context

When you call ```.setTitles(toolbarTitle(), "item selected")``` passing ```null``` as the title of selected items like this: ```.setTitles(toolbarTitle(), null)```, the library gives an exception and the application breaks.

### Steps to reproduce

An example of code that can make the exception to appear
```
 MultiChoiceToolbar multiChoiceToolbar =
                    new MultiChoiceToolbar.Builder(SampleToolbarActivity.this, toolbar)
                            .setTitles(toolbarTitle(), null)
                            .setMultiChoiceColours(R.color.colorPrimaryMulti, R.color.colorPrimaryDarkMulti)
                            .setDefaultIcon(R.drawable.ic_arrow_back_white_24dp, new View.OnClickListener() {
                                @Override
                                public void onClick(View view) {
                                    onBackPressed();
                                }
                            })
                            .build();

        mAdapter.setMultiChoiceToolbar(multiChoiceToolbar);
```
### Current behaviour

The library gives a nullPointerExeception and the application breaks
### Expected behaviour

The library treats the null value and sets the title to a default title (i.e. "" (empty string))

**Comment by dvdciri** [comment]
Thanks for the issue. Honestly I don't think this is a bug, that method is used to append something to the number of items selected, therefore if you don't want to show anything it's an empty string. There's no point of supporting null string, it shouldn't be null.

I'll leave it open with a low priority. Thanks

**Comment by jdamacena** [comment]
that's a good point, I agree with you. Maybe annotating the parameter as
"not null" could be enough.
