### ISSUE TITLE
Hi Davide, I'm facing problems to update the data set of the library after changing my data set. Can you help me, please?

### ISSUE THREAD

**Issue by jdamacena** [dvdciri/MultiChoiceRecyclerView#60]
### Context

I have a `RecyclerView` showing the items of a list, this list is updated when I make CRUD operations trought the `notifyItemInserted(position)` and other methods like that. But, if you make such operations and then try to select all, for example, you'll see that the number of items wasn't updated (if you have 5 items, delete 3, and then `select all` it still will show that you selected 5 items). The worst is that if you insert an item at the end of the list and then try to select it, it wouldn't work because the library thinks that the number of existing items is less than it really is... since the notify methods provided by recyclerView aren't working, what should I do to update the list holded by the library, getting rid of these problems?

**Comment by jdamacena** [comment]
Is there any way to ask the library to recount? Am I missing any command?

**Comment by dvdciri** [comment]
Hi, you're right, there is already an issue opened #49 and a WIP PR that will be update soon #54. Closing this a duplicates, please follow the other issue.
