### ISSUE TITLE
Add one single selection

### ISSUE THREAD

**Issue by ahmadaghazadeh** [dvdciri/MultiChoiceRecyclerView#61]
### Please add one single selection for this component

protected void setMultiChoiceMode (boolean flag) {
     ithis.mIsInMultiChoiceMode =flag;
}

**Comment by ahmadaghazadeh** [comment]
protected void setMultiChoiceMode (boolean flag) {
        ithis.mIsInMultiChoiceMode =flag;
    }

**Comment by dvdciri** [comment]
What do you mean? Can you be more detailed or you can also open PR and contribute to the project. Thanks

**Comment by dvdciri** [comment]
Closing as lack of informations
