### ISSUE TITLE
Problem in selecting item for first time?

### ISSUE THREAD

**Issue by chnouman** [dvdciri/MultiChoiceRecyclerView#64]
### Context
I'm using this library everything goes fine but the issue is for selecting item i have to make a long press
to select first time and other selection goes normal i means by just clicking single time.

### Steps to reproduce
no fancy things just setup the project.

### Current behaviour
while selecting first item i have to long press on the item to select.

### Expected behaviour
i would be able to select first item by simply clicking on item instead of long pressing.

**Comment by adevezin** [comment]
use 
`mAdapter.setSingleClickMode(true);`
to enable that feature

**Comment by dvdciri** [comment]
Correct, that is a feature, you can enable single click mode as per above.
