### ISSUE TITLE
Return toolbar to original state after finishing multiselection

### ISSUE THREAD

**Issue by ScottMellors** [dvdciri/MultiChoiceRecyclerView#9]
Hello, had a relatively easy integration however now after completing the multiselection, I lose the ability to navigate back from the toolbar. 

Is there a way of integrating an actionmode callback or equivalent? Is there a callback for the ending of the multiselect mode? The OnDeselectAll method seemed a likely candidate but there doesn't seem to be.

**Comment by dvdciri** [comment]
Whenever the multi selection count will be equal to 0, it'll automatically reset the toolbar to the original one (if the multi choice toolbar is set).

Can you give more details about what you are doing?

**Comment by dvdciri** [comment]
Closing as don't seems to be a bug or issue.

**Comment by ScottMellors** [comment]
Once all the items are deselected, the home as up indicator on the toolbar that was previously there disappears, I think I might have sorted the issue though.

**Comment by dvdciri** [comment]
Ok thanks, i'll take a look at It asap. Let u know!

**Comment by ScottMellors** [comment]
If you can call the "DeselectAll" when you hit the button, that should be enough to handle it in the short term.

**Comment by dvdciri** [comment]
Why don't you fork It and creat a PR with that change? I'll review It and creare a new patch release!

**Comment by dvdciri** [comment]
Actually that should be already implemented in MultiChoiceToolbarHelper.java:160 when i'm calling deselectAll() and i'll give you the callback. I'll check it anyway

**Comment by dvdciri** [comment]
After a bit of investigation this is related to #7. So it's fixed in v1.1.7

**Comment by ScottMellors** [comment]
Having a dig through the code it seems to have the code to the multichoice listener but for some reason isn't actually being called. See line 135 in MultiChoiceRecyclerView.java, couldn't get the library to compile in my downtime but will try and check if the multiChoiceSelectionListener is initiated.
